### ISSUE TITLE
[STORY] Auto add new issues to AIS project

### ISSUE THREAD

**Issue by tclose** [Australian-Imaging-Service/pipelines#109]
### Description

As a developer, I want all new issues to be added to the AIS project, so that all issues show up there and none are missed.

### Acceptance Criteria

- [ ]  all new issues are assigned to AIS project

### Notes

This is done via GitHub actions (see my attempt here https://github.com/Australian-Imaging-Service/pipelines/blob/main/.github/workflows/assign-to-ais-project.yaml)

**Comment by aswinnarayanan** [comment]
Hi @tclose, there's been some underlying changes between classic and current versions of projects, which might be breaking functionality in the some of the older actions.

For this functionality we'll need a personal access token with repo and project scopes. Which will require a AIS bot user for security. Can we re-use the @AIS-GithubPages bot?

**Comment by tclose** [comment]
I would presume so if that is the easiest, but I don't know anything about GH bots. Is it hard to set up a specific one?

**Comment by tclose** [comment]
Oh, you mean role account. Yes, that should be ok I think

**Comment by tclose** [comment]
I have asked Ryan to create the tokens

**Comment by tclose** [comment]
Can you reuse this token, https://github.com/organizations/Australian-Imaging-Service/settings/secrets/actions?

**Comment by aswinnarayanan** [comment]
Hi @tclose, yes sorry system user / role account.

> Can you reuse this token, https://github.com/organizations/Australian-Imaging-Service/settings/secrets/actions?

I can't see this token. What's the name of the token?

**Comment by tclose** [comment]
This has been implemented
