### ISSUE TITLE
[STORY] Create Pydra Task interface for ANTSRegistration command

### ISSUE THREAD

**Issue by tclose** [Australian-Imaging-Service/pipelines#114]
### Description

As a pipeline developer, I would like to be able to use a ready built Pydra task interface for the `ANTSRegistration` [ANTs](http://stnava.github.io/ANTs/) command, so that I can call that function conveniently from Arcana.

### Acceptance Criteria

- [ ] ANTSRegistration can be successfully called from Pydra
- [ ] all options can be set via the input interface
- [ ] all outputs can be retrieved from output interface

### Notes

This interface should go in the https://github.com/nipype/pydra-ants repository in a module named `preprocess.py` in https://github.com/nipype/pydra-ants/tree/master/pydra/tasks/ants.

Please refer to https://github.com/nipype/pydra-dcm2niix/blob/main/pydra/tasks/dcm2niix/utils.py for the latest style to use while defining the interface and the Pydra docs: https://pydra.readthedocs.io/en/latest/input_spec.html & https://pydra.readthedocs.io/en/latest/output_spec.html for more information (although the docs are a little light)

**Comment by Mahdieh-dst** [comment]
Currently stopped due to a change in our plan: We might write a C++ script that pulls in the required information from the MRTrix source code instead

**Comment by tclose** [comment]
@Mahdieh-dst I have updated this to refer to ANTsRegistration command as no one seems to be working on it at the moment

**Comment by tclose** [comment]
The interface has been created, but still needs testing (see #139)
