### ISSUE TITLE
[STORY] Add all BIDS field map cases to fMRIPrep

### ISSUE THREAD

**Issue by tclose** [Australian-Imaging-Service/pipelines#121]
### Description

As a pipelines user, I want to be able to pass field-maps to the fMRIPrep pipeline in any one of the [4 BIDS cases](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#types-of-fieldmaps) (currently on [Case 2](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#case-2-two-phase-maps-and-two-magnitude-images) is implemented), so that I can run fmriprep on images acquired from a range of MRI scanners.

### Acceptance Criteria

Field-maps can be passed into fmriprep corresponding to BIDS

- [x] 1. [Case 1](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#case-1-phase-difference-map-and-at-least-one-magnitude-image)
- [x] 2. [Case 3](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#case-3-direct-field-mapping)
- [x] 3. [Case 4](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#case-4-multiple-phase-encoded-directions-pepolar)

**Comment by Mahdieh-dst** [comment]
Modified fmriprep.yaml file to pass field-maps for 4 bids cases **on smriprep BRANCH**.
In case 1, magnitude1 image corresponding to the shorter echo time is REQUIRED, but magnitude2 image corresponding to the longer echo time is OPTIONAL. I included both in fmriprep.yaml file.

**Comment by tclose** [comment]
Thanks @Mahdieh-dst ! Can you open a pull request against the main branch?

**Comment by Mahdieh-dst** [comment]
Sure, pull request created.

**Comment by tclose** [comment]
This has been approved
