### ISSUE TITLE
[STORY] Auto updating of features/epics with links from metadata

### ISSUE THREAD

**Issue by tclose** [Australian-Imaging-Service/pipelines#135]
### Metadata

Epic: None
Feature: None
Feature Release: None

### Description

As a project owner, I would like to automated some of the menial actions I need to perform when adding a new story to the issue tracker, to avoid manual errors and make my time more efficient.

### Acceptance Criteria

- [x] 1. Epic and Feature references are extracted from "metadata" section of story template
- [x] 2. Appropriate epic label is added to story
- [x] 3. Link to story is appended to list of stories in corresponding Feature
- [x] 5. Epic references are extracted from "metadata" section of feature template
- [x] 6. Appropriate epic label is added to feature

**Comment by tclose** [comment]
Working model in testing

**Comment by aswinnarayanan** [comment]
@tclose Got a couple of working examples here
[Epic](https://github.com/aswinnarayanan/ais-pipelines/issues/1)
[Feature](https://github.com/aswinnarayanan/ais-pipelines/issues/2)

How does this look?
The workflow will create placeholder comments for newly created Epics and Features so that the Stories/Features comments don't get pushed to the bottom.

**Comment by tclose** [comment]
They look great!

**Comment by aswinnarayanan** [comment]
Thanks @tclose, just two things
1. Do we want this to trigger only when opening issues, or also when editing them?
2. I'd suggest we combine all issue triggers into the same action workflow to reduce change of race conditions. 
This would include moving the auto-labeller from the issue template into this action. And combining with the auto-add-to-projects

**Comment by tclose** [comment]
1. Yes, if it doesn't complicate things, that would be good
2. Good idea, simpler to keep everything in one place too
3. There are just a couple of related actions it would be good to include to
    a. find and apply the appropriate "epic" label: each epic has its own label, which it is labelled with along with "pipelines" and "epic".  Could this be detected and applied to both stories and features?
    b. In the stories table of the project view, there is a "feature" column (see screenshot). Could this be updated with #<feature-num>.<release-num>?
<img width="1431" alt="Screen Shot 2022-09-06 at 8 26 15 am" src="https://user-images.githubusercontent.com/1054870/188517349-5686c4d2-703f-4ed7-be38-7a8ea11a8e60.png">

**Comment by aswinnarayanan** [comment]
Hi @tclose, I haven't got 3a and 3b done in this pull request yet. Might get this one pushed through first

**Comment by tclose** [comment]
#152 addresses this issue

**Comment by tclose** [comment]
The remaining tasks have been shifted to #175
