### ISSUE TITLE
[STORY] Port ANTs interfaces used in sMRIPrep - part I

### ISSUE THREAD

**Issue by tclose** [Australian-Imaging-Service/pipelines#141]
### Metadata

Epic: #17 
Feature: #79 
Feature Release: 1

### Description

As a developer, I want to be able to use the Pydra task interfaces listed below, so I can port the workflows used in sMRIPrep

The second part of this story is covered by #149 

### Acceptance Criteria

Port the following ANTs Nipype interfaces to Pydra with appropriate tests

- [x] Atropos
- [x] N4BiasFieldCorrection
- [x] AI

**Comment by Mahdieh-dst** [comment]
Pull request for "test" branch created at (https://github.com/nipype/pydra-ants)
