### ISSUE TITLE
[STORY] Port ANTs interfaces used in sMRIPrep - part II

### ISSUE THREAD

**Issue by tclose** [Australian-Imaging-Service/pipelines#149]
### Metadata

Epic: #17 
Feature: #79 
Feature Release: 1

### Description

As a developer, I want to be able to use the Pydra task interfaces listed below, so I can port the workflows used in sMRIPrep

This part II of this feature following up from #141 

### Acceptance Criteria

Port the following ANTs Nipype interfaces to Pydra with appropriate tests

- [x] ImageMath
- [x] MultiplyImages
- [x] ThresholdImage

**Comment by Mahdieh-dst** [comment]
Pull request created for "test" branch at (https://github.com/nipype/pydra-ants)

**Comment by tclose** [comment]
This PR is good to go, I just can't merge it as I have lost my admin rights
