### ISSUE TITLE
[FEATURE] Canvassing user requirements

### ISSUE THREAD

**Issue by mrusyd** [Australian-Imaging-Service/pipelines#16]
### Description
AIS/NIF users need to be engaged as part of the funding proposal in order to prioritise the complex analysis workflows to be implemented.

### Benefit Hypothesis

If users are properly engaged to prioritise the most desirable analysis methods, then the pipelines developed will better suit the user base and should have increased uptake.

### Acceptance Criteria

- [ ] All NIF and AIS nodes should be consulted
- [ ] Comprehensive list of all requested methods
- [ ] Prioritised list of methods to be implemented

### Stories

- [x] Email nodes asking for most desirable analysis methods
- [x] Collate responses
- [x] Prepare report for Academic Oversight Committee and node directors

**Comment by tclose** [comment]
Report has been generated and passed to Fernando to disseminate to node directors
