### ISSUE TITLE
[STORY] Add ability to download OpenNeuro datasets in medimages4tests

### ISSUE THREAD

**Issue by tclose** [Australian-Imaging-Service/pipelines#213]
### Metadata

Epic: #17 
Feature: #79 
Feature Release: 1
Required knowledge: deep

### Description

As a Pydra interface developer, I want to be able to easily access a number of sample neuro MRI datasets, so that I can write live tests for the interfaces I am developing.

### Acceptance Criteria

- [ ] 1. Open neuro-MRI datasets are accessible via medimages4tests
- [ ] 2. Lists of images of the same type are provided in a way that it is easy to create a parameterised pytest fixture

**Comment by arkiev** [comment]
this has been implemented in latest versions
