### ISSUE TITLE
[STORY] Create pull-request on Pydra repository regarding mandatory XOR inputs

### ISSUE THREAD

**Issue by tclose** [Australian-Imaging-Service/pipelines#223]
### Metadata

Epic: #17 
Feature:
Feature Release:
Required knowledge: shallow or mid-level or deep

### Description

We identified a possible issue with Pydra task input fields checking.

Input fields can be marked as 'mandatory' as well as 'mutually exclusive'.
If 
1. field_A is mandatory
2. field_B is mandatory
3. field_A and field_B are 'mutually exclusive'

then only field_A or field_B is needed, not both.

Nipype follows this behavior, but it seems like `check_fields_input_spec()` of the Pydra engine (pydra/pydra/engine/specs.py) is checking those conditions sequentially, not concurrently.
Compared with `_check_mandatory_inputs()` (nipype/interfaces/base/core.py)

### Acceptance Criteria

- [x] 1. Create unit tests to check the issue described
- [x] 2. Propose a fix

### Blocked by

- [ ]

**Comment by ablachair** [comment]
Pull request created

https://github.com/nipype/pydra/pull/595

**Comment by tclose** [comment]
PR has been merged
