### ISSUE TITLE
magic number error with `.mgz` file format

### ISSUE THREAD

**Issue by arkiev** [Australian-Imaging-Service/pipelines#241]
The following code was used to import .mgz file format
`from fileformats.medimage import NiftiGz, MghZip` 

This resulted in the following error when referring to a file of type .mgz:

`raise FormatMismatchError(
fileformats.core.exceptions.FormatMismatchError: Magic number of file "1f8b0800" doesn't match expected "504B0304"`

Workaround has been to convert relevant .mgz to .nii, but ideally we would avoid this intermediate step

To reproduce this error, run `T1_pipeline_pydra.py` and replace 
- [ ] norm_image and aparc_aseg to filetype .mgz
- [ ] update the input_spec to reflect this change in filetype

**Comment by tclose** [comment]
This has been fixed by changing it from Zip to Gz
