### ISSUE TITLE
[STORY] Adapting JupyterHub plugin so that the worker nodes can be launched on K8s

### ISSUE THREAD

**Issue by tclose** [Australian-Imaging-Service/pipelines#250]
### Metadata

Epic:
Feature: #248
Feature Release:
Required knowledge: deep

### Description

Adapt the JupyterHub plugin so that worker nodes can be launched on Kubernetes clusters

### Acceptance Criteria

- [x] 1. JupyterHub plugin should be able to be installed on AIS-k8s configuration (touch base with @dean-taylor on how to set up dev instanced on microk8s)
- [x] 2. Need to be able to specify the computation resources assigned to each worker node (e.g. small, medium, large, etc...)
- [x] 3. Project data needs to be accessible from launched worker nodes
- [x] 4. NeuroDesk container should be able to be launched from JupyterHub plugin
- [x] 5. New Docker images need to be able to be installed through UI

### Blocked by

- [ ]

**Comment by anzhao** [comment]
Installed and deployed the JupyterHub on my local microk8s cluster (see below). 

![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/f7837f78-b4b5-47cc-a5ed-cd7dc6fe70b9)

**Comment by tclose** [comment]
👍

From: An Zhao ***@***.***>
Date: Monday, 6 November 2023 at 3:05 pm
To: Australian-Imaging-Service/pipelines ***@***.***>
Cc: Tom Close ***@***.***>, Author ***@***.***>
Subject: Re: [Australian-Imaging-Service/pipelines] [STORY] Adapting JupyterHub plugin so that the worker nodes can be launched on K8s (Issue #250)

Installed and deployed the JupyterHub on my local microk8s cluster (see below).

[Image]<https://user-images.githubusercontent.com/4756925/280591308-f7837f78-b4b5-47cc-a5ed-cd7dc6fe70b9.png>

**Comment by anzhao** [comment]
Set up Microk8s, XNAT, JupyterHub, Harbor and so on on our Ubuntu instance of AWS, as it has more resources for deploying and testing purpose. 

![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/34aacb2d-400f-463c-9c38-ab693cf39ff4)

**Comment by anzhao** [comment]
The cause of crashloopback error is related to the default value of periodSeconds of startup probe. The default value of periodSeconds (Defines the frequency (seconds) of performing probes) is 10. After increasing it to 60, the XNAT instance is running without issues.

![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/c5f0bcb8-11a9-4367-8d67-2ebe724989d8)


![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/26e2a465-411d-4433-ab5d-7ed7dd15b665)

**Comment by anzhao** [comment]
The current plugin uses the [SwarmSpawner](https://jupyterhub-dockerspawner.readthedocs.io/en/latest/spawner-types.html#swarmspawner)to launch single user notebook servers as Docker Swarm mode services. This allows for running JupyterHub in a swarm so that notebook containers can be run on any of multiple servers.

**Comment by anzhao** [comment]
Build my own docker image of XNAT with latest version of source code xnat-web-1.8.9.2.war (downloaded from https://bitbucket.org/xnatdev/xnat-web/downloads/) and container service plugin (downloaded from https://bitbucket.org/xnatx/xnat-jupyterhub-plugin/downloads/) and deployed XNAT version 1.8.9.2 to Kubernetes. 



![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/76cf270e-ee08-43d9-87d1-a563ab2581c3)

**Comment by anzhao** [comment]
Deploy JupyterHub on k8s and make sure that the XNAT and JupyterHub are on the same namespaces.



![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/1b3659a9-04eb-46d7-84b6-b71f31290c01)

**Comment by anzhao** [comment]
JupyterHub server running on k8s.


![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/a9a9f0c8-4224-4873-afce-1aed0dbf1b0a)

The correct JupyterHub API endpoint is http://localhost:8080/hub/api/ for my instance and it returns:


![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/b9195ae6-34b0-4ed0-ba6d-ae9d70526bd4)

**Comment by anzhao** [comment]
The following is the detailed document I created to run XNAT and JupyterHub on K8s.

[xnat-jupyterhub-k8s-integration.pdf](https://github.com/Australian-Imaging-Service/pipelines/files/13723430/xnat-jupyterhub-k8s-integration.pdf)

**Comment by anzhao** [comment]
The correct path for establishing the connection between XNAT and JupyterHub server is as follows:
http://hub:8081/jupyterhub/hub/api (which is a private internal API for communicating with different pods under one k8s cluster).
Once you had set the correct API path, it will return the hub version number 4.0.2 and a green tick shown as below:

![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/ae3f1c09-9248-4f23-89e1-8aa43e0316d6)

**Comment by anzhao** [comment]
Successfully launched the JupyterHub within XNAT.

![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/a78461ee-e069-41b2-86ae-39303440fa7c)

**Comment by anzhao** [comment]
![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/5aa1f04a-78ec-45a6-bb50-957fa8e51a0c)



![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/12b7eb2b-abdf-41db-aa4c-a53b0d067d47)



![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/722ff166-522e-459a-a695-c6d1f8e39b0b)

**Comment by anzhao** [comment]
Added the Neurodesk image to JupyterHub.


![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/e038cb3c-ec6d-4d33-8bea-2697c85135c6)

**Comment by anzhao** [comment]
Use the following Dockerfile as a template to build a JupyterHub compabatible image and it is start with based image jupyter datascience notebook.
**********************************************************************
FROM jupyter/datascience-notebook:hub-3.0.0

COPY --chown=${NB_UID}:${NB_GID} requirements.txt /tmp/

RUN python3 -m pip install --requirement /tmp/requirements.txt && \
    python3 -m pip install vnmd/neurodesktop:latest && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}" && \
    rm /tmp/requirements.txt \

*********************************************************
When building the image such as NeuroDesk image, it will be depends on the following:
xnat==0.4.3
pyxnat>=1.4
pydicom>=2.3.0
jupyterlab-git>=0.41.0

**********************************************************************
[XNATpy](https://xnat.readthedocs.io/en/latest/) version 0.4.3 introduced support for the XNAT JupyterHub integration. The [pyxnat](https://pyxnat.github.io/pyxnat/) package is serves as an additional Python client for XNAT. The [pydicom](https://pydicom.github.io/) package offers functionality for interacting with DICOM data in Python. Additionally, the [jupyterlab-git ](https://pypi.org/project/jupyterlab-git/)extension enables Git integration within JupyterLab.

Build you image by type the command, such as "docker build -t your-image-name:tag .":


![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/1696d6cd-24b4-4d0a-868a-03f7a7dc3440)

Verify the image you built by running "docker run".


![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/c5f255a3-426a-47ac-b02a-fbc18cb7e6cc)

**Comment by anzhao** [comment]
Launch the NeuroDesk from XNAT:


![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/9f8052dd-ca21-41f8-b26b-4ff343b3b7b5)

**Comment by anzhao** [comment]
![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/f637ce8e-35ed-4b57-912e-c85926a8b8a3)

**Comment by anzhao** [comment]
![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/12c6b5e3-b0cf-4b8b-a8bc-2ae578c50513)

**Comment by anzhao** [comment]
After setup CVMFS and jupyter user write permission, the Neurodesk applications are available for end users.


![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/be286b62-531d-4562-86e2-1e8f2bc36494)

**Comment by tclose** [comment]
Needs to be checked with @aswinnarayanan to see whether everything is working correctly but otherwise looks good!
