### ISSUE TITLE
[STORY] Familiarising with AIS Helm chart

### ISSUE THREAD

**Issue by tclose** [Australian-Imaging-Service/pipelines#255]
### Metadata

Epic: #34 
Feature: #248 
Feature Release:
Required knowledge: deep

### Description

Time is required to familiarise with K8s commands and the AIS helm chart before work is done to integrate the jupyterhub

**Comment by anzhao** [comment]
Went through the LinkedIn online course: "Learning Kubernetes", "Kubernetes for Java Developers", "Kubernetes Essential Tools", "Kubernetes: Package Management with Helm". Reviewed the official Kubernetes document and help resource, in particularly, how to debug a pod (https://kubernetes.io/docs/tasks/debug/debug-application/debug-running-pod/).
