### ISSUE TITLE
[STORY] Create a video demo showing JupyterHub/NeuroDesk launch for presentation

### ISSUE THREAD

**Issue by tclose** [Australian-Imaging-Service/pipelines#265]
### Metadata

Epic: 
Feature: None
Feature Release:
Required knowledge: shallow or mid-level or deep

### Description

Ryan needs to demonstrate the working JupyterHub/NeuroDesk solution via a short video

### Acceptance Criteria

- [ ] 1. Demonstrates how to launch a NeuroDesk container from XNAT
- [ ] 2. Demonstrates how to run a viewing tool, e.g. 3D slicer
- [ ] 3. Demonstrates how to access data in the container

### Blocked by

- [ ]

**Comment by anzhao** [comment]
A video demo for launch of NeuroDesk within XNAT has been provided to Ryan.

**Comment by tclose** [comment]
Need to test environment modules on non-M1 chip system
