### ISSUE TITLE
[STORY] Create cron/batch job to automatically update NeuroDesk

### ISSUE THREAD

**Issue by tclose** [Australian-Imaging-Service/pipelines#266]
### Metadata

Epic:
Feature:
Feature Release:
Required knowledge: shallow or mid-level or deep

### Description

In order to ensure each node is running the latest version of NeuroDesk, we would like a script to automatic update to run regularly to pull in the most recent container image, which could be installed within the k8s cluster that runs XNAT.

### Acceptance Criteria

- [ ] 1. Script downloads latest vesrion of NeuroDesk to cluster
- [ ] 2. Local system admin should have control whether to stop this process and fix the version if required

### Blocked by

- [ ]

**Comment by anzhao** [comment]
In the progress of set up Kubernete CronJob in k8s cluster to automate pulling the latest version of NeuroDesk image.

**Comment by anzhao** [comment]
Create the Python script to pull the image from NeuroDesk docker hub:

![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/c8b708d2-3c4d-45da-8c7a-69c7a88246b8)

Build the image of auto pull NeuroDesk to be run by CronJob on K8s

![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/63c8a379-0625-4663-87a1-75a9586f233b)

Create the cronjob on K8s:

![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/363c475a-2339-4619-8e1b-5e55fcaf02aa)
