### ISSUE TITLE
[STORY] Check with NeuroDesk team that XNAT-launched containers are fully operational

### ISSUE THREAD

**Issue by tclose** [Australian-Imaging-Service/pipelines#267]
### Metadata

Epic:
Feature:
Feature Release:
Required knowledge: shallow or mid-level or deep

### Description

Ensure that XNAT-launched NeuroDesk containers are working as expected. This could be best done by checking in with @aswinnarayanan for him to test it.

### Acceptance Criteria

- [ ] 1. NeuroDesk team are satisifed by the performance of NeuroDesk in XNAT.

**Comment by anzhao** [comment]
I have emailed to Neurodesk team at UQ for singularity issues and confirmed that at this stage it does not support to run on M1 chip of Mac. I am in the progess of setup the XNAT, JupyterHub and Neurodesk to run Ubuntu on AWS.

**Comment by anzhao** [comment]
XNAT, JupyterHub, Neurodesk and CVMFS all have been migrated to Ubuntu server on AWS. Now, all of them are operating under Ubuntu X86 system arch, the following video shows the launch of Neurodesk and its applications.  

https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/ce3e3836-54ce-4f42-a34a-b370a9031505
