### ISSUE TITLE
[STORY] Setup and test NeuroDesk integration with non-M1 chip

### ISSUE THREAD

**Issue by tclose** [Australian-Imaging-Service/pipelines#274]
### Metadata

Epic: #34 
Feature: #54 
Feature Release:
Required knowledge: mid-level

### Description

Need to test NeuroDesk integration on non-M1 chip system, so need to set up external test environment

### Acceptance Criteria

- [x] 1. Test NeuroDesk integration

### Blocked by

- [ ]

**Comment by anzhao** [comment]
Neurodesk has been setup on Ubuntu server and confirmed it works under X86 system arch (see below).

![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/7299eb2b-2aa7-49e0-a428-6863b033ec67)

**Comment by tclose** [comment]
Nice work!
