### ISSUE TITLE
[STORY] Upgrade MSBase to 1.8.*

### ISSUE THREAD

**Issue by tclose** [Australian-Imaging-Service/pipelines#277]
### Metadata

Epic:
Feature:
Feature Release:
Required knowledge: shallow or mid-level or deep

### Description

Update MSBase XNAT to 1.8

**Comment by tclose** [comment]
* Created UAT environment installed with prod database and subset of prod data in EFS
* Handover to MSBIR for testing
* Outstanding issues found, including incompatibility between download client and latest XNAT API (emailed flywheel for updated client)

**Comment by tclose** [comment]
Possible solution to use old plugins

**Comment by fxusyd** [comment]
Updated plugins were provided but still failed testing in our dev environment.

**Comment by fxusyd** [comment]
All Msbir deployment in AU, EU and US are upgraded and verified by SNAC.
