### ISSUE TITLE
[STORY] Include JupyterHub image within AIS helm chart

### ISSUE THREAD

**Issue by tclose** [Australian-Imaging-Service/pipelines#287]
### Metadata

Epic: #34 
Feature: #54 

### Description

* Get URL to latest JupyterHub image (@anzhao)
* Get URL to latest NeuroDesk (@anzhao)
* Adapt JupyterHub helm chart to work with USyd EKS config

### Acceptance Criteria

- [ ] 1. JupyterHub + neurodesk runs on USyd EKS

**Comment by anzhao** [comment]
The JupyterHub Helm chart is here: https://bitbucket.org/xnat-containers/xnat-jupyterhub/src/main/xnat-jupyterhub-chart/values.yaml
The latest version of NeuroDesk image is here: https://hub.docker.com/layers/vnmd/neurodesktop/2024-04-04/images/sha256-5f7b1836e5dc33945d27bfbf91011bb21c4019e7c650b02f22edf313b1d33db4?context=explore

**Comment by fxusyd** [comment]
Identified issues within the Jupyterhub Helm chart to run Juypterhub as production system with auto scaling worker nodes. Issues and desirable enhancement were submitted to both Flywheel and Andy.

**Comment by tclose** [comment]
Waiting on Flywheel to fix some bugs
