### ISSUE TITLE
[STORY] Loosen NFS permissions on TBP staging server dev VM

### ISSUE THREAD

**Issue by tclose** [Australian-Imaging-Service/pipelines#289]
### Metadata

Epic: #271 
Feature: #273 

### Description

Loosen permissions on TBP development VM so that `/vol/vmhost/kubernetes` directory is accessible to root user

### Acceptance Criteria

- [ ] 1.  root user can access `/vol/vmhost/kubernetes`

**Comment by dean-taylor** [comment]
Add Dev VM to the NFS client group with full access to the Kubernetes share.
`Set-NfsClientgroup -ClientGroupName kubernetes -AddMember`

Requires test to validate outcome works as expected.

**Comment by tclose** [comment]
Thanks Dean, I can access the `kubernetes` mount now :)
