### ISSUE TITLE
[FEATURE] Implement the Whole Slide Imaging (WSI) Datatype and new External Camera Protected (ECP) Datatype in XNAT.

### ISSUE THREAD

**Issue by anzhao** [Australian-Imaging-Service/pipelines#297]
### Metadata

Epic: XNAT datatype.

### Description
New XNAT data types are needed to store various kinds of research data within the XNAT platform. 

### Development Stages

1. Creating a New Data Type Schema in XNAT. Define its structure using an XML schema document (XSD format). This schema specifies the data type’s format and elements. The following is an example:

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xnat:Project ID="AIS-111" secondary_ID="AIS experiment" active="1" xmlns:arc="http://nrg.wustl.edu/arc" xmlns:val="http://nrg.wustl.edu/val" xmlns:pipe="http://nrg.wustl.edu/pipe" xmlns:pixi="http://nrg.wustl.edu/pixi" xmlns:icr="http://icr.ac.uk/icr" xmlns:ais="http://australian-imaging-service.github.io/" xmlns:wrk="http://nrg.wustl.edu/workflow" xmlns:scr="http://nrg.wustl.edu/scr" xmlns:xdat="http://nrg.wustl.edu/security" xmlns:cat="http://nrg.wustl.edu/catalog" xmlns:prov="http://www.nbirn.net/prov" xmlns:xnat="http://nrg.wustl.edu/xnat" xmlns:xnat_a="http://nrg.wustl.edu/xnat_assessments" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://nrg.wustl.edu/workflow http://localhost/schemas/workflow.xsd http://nrg.wustl.edu/catalog http://localhost/schemas/catalog.xsd http://nrg.wustl.edu/pipe http://localhost/schemas/repository.xsd http://nrg.wustl.edu/pixi http://localhost/schemas/pixi.xsd http://nrg.wustl.edu/scr http://localhost/schemas/screeningAssessment.xsd http://nrg.wustl.edu/arc http://localhost/schemas/project.xsd http://icr.ac.uk/icr http://localhost/schemas/roi.xsd http://nrg.wustl.edu/val http://localhost/schemas/protocolValidation.xsd http://nrg.wustl.edu/xnat http://localhost/schemas/xnat.xsd http://australian-imaging-service.github.io/ http://localhost/schemas/melanoma_imaging.xsd http://nrg.wustl.edu/xnat_assessments http://localhost/schemas/assessments.xsd http://www.nbirn.net/prov http://localhost/schemas/birnprov.xsd http://nrg.wustl.edu/security http://localhost/schemas/security.xsd">
 \<xnat:name>AIS research project</xnat:name>
 \<xnat:PI>
 \<xnat:title>Mr</xnat:title>
 \<xnat:firstname>An</xnat:firstname>
 \<xnat:lastname>ZHAO</xnat:lastname>
 \<xnat:institution>Sydney Uni</xnat:institution>
 \</xnat:PI>
 \<xnat:custom_fields>{}</xnat:custom_fields>
 \</xnat:Project>

2. Create an XNAT plugin: 
The XNAT plugin implemented is a Java archive (JAR) file containing the schema file and additional components for displaying and managing your data type within XNAT.

3. Deploy the XNAT plugin:
Once the plugin is built, deploy it on your XNAT server. This process involve copying the JAR file to the plugin folder and restarted your XNAT server to make sure that new data type is loaded into your XNAT system.

**Comment by anzhao** [comment]
I have turned on the Whole Slide Imaging (WSI) Datatype (xnat:smSessionData) on our XNAT dev server (see image below). 
![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/b18e3804-8b1a-4a30-a843-73f7878c0f43)

I obtained some slide image data from idc open data shared on S3 by installing s5cmd and running the following command:
![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/1d5d2a8f-6d30-4a6b-ba92-0598cec5d21e)

I upload the slide image data to our dev test server and confirmed that XNAT OHIF viewer not support it.
![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/0f7cbea9-bc97-462f-9432-ee867ad029d3)

By adding QuPath to Neurodesk should be addressed the above issue or alternatively: https://github.com/ImagingDataCommons/slim, this slim code repo seems to address this issue as well.

**Comment by anzhao** [comment]
External Camera Protected Session data (XCPsession) and External Camera Protected Scan data (XCPscan) both limit the access of the datatype by IP address (see below).

![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/0eb59666-16f5-4eba-8eda-f5a08e52fb92)

**Comment by RyanPSullivan7** [comment]
In the first instance we won't need it limited by IP as @dean-taylor still needs to look at how we segregate container access, but the creation of the separate data is needed as we will toggle the restrict by IP address at a later date.

**Comment by anzhao** [comment]
**Create the NEW xcp session data type and loaded into the local XNAT:**


![Image](https://github.com/user-attachments/assets/3c94e1a8-c4f3-46fc-ab9d-30f7355c3d84)



![Image](https://github.com/user-attachments/assets/b603675f-3cbb-4ca5-8215-4fb6777d8eea)

**Comment by anzhao** [comment]
**On the backend database, it will create tables of ais_xcpSessionData_meta_data, ais_xcpSessionData_history, ais_xcpSessionData and so on to add this new data type to XNAT.** 

![Image](https://github.com/user-attachments/assets/ec43f51f-461a-47ec-833d-191ae8d4182c)

**Comment by tclose** [comment]
Implemented plugin, need to put on GitHub and create GH action to build
