### ISSUE TITLE
[STORY] Setup deidentification script for AILDR project

### ISSUE THREAD

**Issue by tclose** [Australian-Imaging-Service/pipelines#299]
### Metadata

Epic:
Feature:
Feature Release:
Required knowledge: shallow or mid-level or deep

### Description

**User Stories** are the primary means of expressing needed functionality. Since they focus on the user as the subject of interest, and not the system, user stories are value and customer-centric. Recommended form is the "user-voice form":

	As a (user role), I want to (activity), so that (business value)
By using this format, the teams are guided to understand who is using the system, what they are doing with it, and why they are doing it.

**Enabler Stories** are written to support exploration, architecture, or infrastructure. Enabler stories may be expressed in technical rather than user-centric language. Enabler stories are demonstrated just like user stories, typically by showing the knowledge gained, artifacts produced, or the user interface, stub, or mock-up.

### Acceptance Criteria
Acceptance criteria is used to confirm that the story was completed correctly. Criteria can be written in any format, or a "given-when-then" form may be used:

	Given *some context*
	When *some action is carried out*
	Then *a particular set of observable consequences should obtain*

- [ ] 1. 

### Blocked by

- [ ]

**Comment by anzhao** [comment]
In XNAT, we recommended to setup the Anonymization Script at project level instead of whole site level. In XNAT, first disable the site-wide anonymization by going to Site Administration. -->  Manage Data (Session Upload, Import & Anonymization) -->. Disable Site-Wide Anonymization Script (see below).

![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/39568800-a120-4b46-878d-768fdc35b0ac)

In the meanwhile, go to the specific project you want to apply anonymization (project --> Manage --> Anonymization Script), then add your own script with the specific private/protected health info you want to remove (see below).

![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/32d74b94-b2be-4951-a3ef-3e446f5e3077)

**Comment by anzhao** [comment]
The following de-identification script will be used to remove the specified PHI:

version "6.1"
project != "Unassigned" ? (0008,1030) := project
//Patient’s Name
(0010,0010) := subject
//Patient ID
(0010,0020) := session
//Patient’s Birth Date
(0010,0030) := ""
//Referring Physician’s Name, set to empty
(0008,0090) := ""
//Institution Name
(0008,0080) := ""
//Institution Address
(0008,0081) := ""
// Patient's Sex
(0010,0040) := ""
//Patient's Age
(0010,1010) := ""

The above script will remove the Patient Name, Patient ID, Patient Birth Date, Referring Physician Name, Institution Name, Institution Address, Patient Sex and Age.

The following is a testing and comparison of before and after applying the anonymization script.

Before apply the script, we can find all the private info above, such as patient name, DOB and so on (see below).

![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/3cfe1c30-f0ff-419d-88a6-d28eca9e406a)

After apply the script, we confirm that all the specified PHI are removed (see below).

![Image](https://github.com/Australian-Imaging-Service/pipelines/assets/4756925/7f476256-63c9-41df-9290-845ecfc33c36)

**Comment by anzhao** [comment]
# Include additional tags specified by Dan to the de-identification script (see below).

```
version "6.1"
project != "Unassigned" ? (0008,1030) := project
(0010,0010) := subject           // Patient's Name
(0010,0020) := session          // Patient ID
(0400,0561) := ""           // Original Attributes Sequence
(0008,0014) := ""         // Instance Creator UID
(0008,0050) := ""          // Accession Number
(0008,1111) := ""          // Referenced Performed Procedure Step SQ
(0008,1120) := ""          // Referenced Patient SQ
(0008,1140) := ""         // Referenced Image SQ
(0008,0090) := ""           // Referring Physician's Name
(0008,0096) := ""           // Referring Physician Identification SQ
(0008,1032) := ""         // Procedure Code SQ
(0008,1048) := ""        // Physician(s) of Record
(0008,1049) := ""           // Physician(s) of Record Identification SQ
(0008,1050) := ""            // Performing Physicians' Name
(0008,1052) := ""           // Performing Physician Identification SQ
(0008,1060) := ""           // Name of Physician(s) Reading Study
(0008,1062) := ""           // Physician(s) Reading Study Identification SQ
(0008,1110) := ""           // Referenced Study SQ
(0008,1111) := ""            // Referenced Performed Procedure Step SQ
(0008,1250) := ""            // Related Series SQ
(0008,9092) := ""           // Referenced Image Evidence SQ
(0010,0021) := ""            // Issuer of Patient ID
(0010,0030) := ""           // Patient's Birth Date
(0010,0032) := ""           // Patient's Birth Time
(0010,0050) := ""          // Patient's Insurance Plan Code SQ
(0010,0101) := ""           // Patient's Primary Language Code SQ
(0010,1000) := ""           // Other Patient IDs
(0010,1001) := ""           // Other Patient Names
(0010,1002) := ""           // Other Patient IDs SQ
(0010,1005) := ""           // Patient's Birth Name
(0010,1010) := ""           // Patient's Age
(0010,1040) := ""           // Patient's Address
(0010,1060) := ""           // Patient's Mother's Birth Name
(0010,1080) := ""           // Military Rank
(0010,1081) := ""           // Branch of Service
(0010,1090) := ""           // Medical Record Locator
(0010,2000) := ""            // Medical Alerts
(0010,2110) := ""            // Allergies
(0010,2150) := ""            // Country of Residence
(0010,2152) := ""          // Region of Residence
(0010,2154) := ""          // Patient's Telephone Numbers
(0010,2160) := ""          // Ethnic Group
(0010,2180) := ""          // Occupation
(0010,21A0) := ""          // Smoking Status
(0010,21B0) := ""          // Additional Patient History
(0010,21C0) := ""          // Pregnancy Status
(0010,21D0) := ""          // Last Menstrual Date
(0010,21F0) := ""          // Patient's Religious Preference
(0010,2203) := ""          // Patient's Sex Neutered
(0010,2297) := ""          // Responsible Person
(0010,2298) := ""          // Responsible Person Role
(0010,2299) := ""          // Responsible Organization
(0020,9221) := ""          // Dimension Organization SQ
(0020,9222) := ""          // Dimension Index SQ
(0038,0010) := ""          // Admission ID
(0038,0011) := ""          // Issuer of Admission ID
(0038,0060) := ""          // Service Episode ID
(0038,0061) := ""          // Issuer of Service Episode ID
(0038,0062) := ""          // Service Episode Description
(0038,0500) := ""          // Patient State
(0038,0100) := ""          // Pertinent Documents SQ
(0040,0260) := ""          // Performed Protocol Code SQ
(0088,0130) := ""          // Storage Media File-Set ID
(0088,0140) := ""          // Storage Media File-Set UID
(5200,9229) := ""          // Shared Functional Groups SQ
```
