### ISSUE TITLE
[STORY] Check auto-generated pipelines documentation for completeness

### ISSUE THREAD

**Issue by tclose** [Australian-Imaging-Service/pipelines#45]
### Description

Documentation for AIS pipelines is being auto-generated from YAML recipes at https://australian-imaging-service.github.io/user_docs/pipelines/. We need to check to see whether generated documentation is sufficient.

### Acceptance Criteria

- [x] 1. Ascertain whether users are are able to get all the information they need from the generated documentation
- [x] 2. Check whether the layout of generated pages is easy to scan

**Comment by civier** [comment]
Hi Tom,

I made a PDF out of the fmriprep page and put some comments. Let me know if you cannot open the document or if the comments don't come up.
[fmriprep _ Australian Imaging Service-OC.pdf](https://github.com/Australian-Imaging-Service/pipelines/files/9256815/fmriprep._.Australian.Imaging.Service-OC.pdf)

Cheers,
Oren

**Comment by civier** [comment]
Another thing:
Also make sure that the help page itself can be updated without the need to rebuild the package. Often you just want to change something in the instructions, and it's silly to rebuild everything just for that.

**Comment by tclose** [comment]
Thanks for the comments Oren, they are really useful. I will make a new story to address them. I run a check to see whether the pipelines need to be rebuilt and skip them if there aren't changes so could ignore certain fields. However, some of these fields will be exposed in the UI so would require a rebuild of the image
