### ISSUE TITLE
[STORY] Mrtrix3 connectome BIDS app pipeline spec

### ISSUE THREAD

**Issue by tclose** [Australian-Imaging-Service/pipelines#59]
### Description

As a researcher, I want to be able to run "MRtrix3 connectome" using the XNAT container service, so that I can conveniently run it over all the sessions in my project. I would like to input all relevant scan types

- T1-weighted
- dwi images

### Acceptance Criteria

- [x] "MRtrix3 connectome" image builds and launches successfully
- [x] test is added with suitable test data

**Comment by Mahdieh-dst** [comment]
Currently debugging with Tom
