### ISSUE TITLE
[STORY] Deploy diffusion MRI preprocessing BIDS app (qsiprep) in XNAT container service

### ISSUE THREAD

**Issue by tclose** [Australian-Imaging-Service/pipelines#61]
### Description

As a researcher, I want to be able to run a diffusion preprocessing BIDS app (e.g. dmriprep or qsiprep) using the XNAT container service, so that I can conveniently run it over all the sessions in my project. I would like to input all relevant scan types

- T1-weighted
- diffusion-weighted MRI

### Acceptance Criteria

- [x] diffusion preprocessing BIDS app (qsiprep) image builds and launches successfully on a number of different XNAT projects/acquisition protocols
- [x] tests for qsiprep are added to repo

**Comment by Mahdieh-dst** [comment]
Currently debugging with Tom
