### ISSUE TITLE
[STORY] antsCorticalThickness BIDS app pipeline spec

### ISSUE THREAD

**Issue by tclose** [Australian-Imaging-Service/pipelines#63]
### Description

As a researcher, I want to be able to run the [antsCorticalThickness](https://github.com/bids-apps/antsCorticalThickness) BIDS app using the XNAT container service, so that I can conveniently run it over all the sessions in my project. I would like to input all relevant scan types

- T1-weighted

### Acceptance Criteria

- [ ] antsCorticalThickness BIDS app image builds and runs successfully on a number of different XNAT projects/acquisition protocols

**Comment by Mahdieh-dst** [comment]
Created a branch named antsCorticalThickness, made antscorticalthickness.yaml file and put the relevant test data in the test folder, and ran the unit test. ---Currently, debugging!----
